version: "3.9"

services:

  # ───────────── DATABASES ─────────────

  users-db:
    image: mysql:8.0
    container_name: users-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users_db
    ports:
      - "3307:3306"
    volumes:
      - users_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  dorm-db:
    image: mysql:8.0
    container_name: dorm-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dorm_db
    ports:
      - "3308:3306"
    volumes:
      - dorm_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  nutrition-db:
    image: mysql:8.0
    container_name: nutrition-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nutrition_db
    ports:
      - "3309:3306"
    volumes:
      - nutrition_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s


  # ───────────── APPLICATIONS ─────────────

  users-app:
    build: ./users
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://users-db:3306/users_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      NUTRITION_SERVICE_URL: http://nutrition-app:8082
    depends_on:
      users-db:
        condition: service_healthy

  dorm-app:
    build: ./dorm
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://dorm-db:3306/dorm_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 8081
    depends_on:
      dorm-db:
        condition: service_healthy

  nutrition-app:
    build: ./nutritionDepartment
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://nutrition-db:3306/nutrition_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 8082
    depends_on:
      nutrition-db:
        condition: service_healthy

volumes:
  users_db_data:
  dorm_db_data:
  nutrition_db_data:
